vae:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 3
      ####
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    wrap: True
    train:
      # vaeはtextデータはいらない
      target: ldm.data.localillustnotext.LocalIllustBaseNoText
      params:
        size: 256
        data_root: ./traindata
    validation:
      target: ldm.data.localillustnotext.LocalIllustBaseNoText
      params:
        size: 256
        # trainと重ならないやつ指定しよう
        data_root: ./traindata

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  modelcheckpoint:
    params:
      every_n_train_steps: 500

  trainer:
    max_steps: 1000000
    benchmark: True
    # truth_batch_size = batch_size * accumulate_grad_batches
    accumulate_grad_batches: 3

opt:
  debug: True
  seed: 35
  # CPUの場合はFalse, GPUの場合はGPUのIDを指定
  gpus: 0, 
  logdir: ./logs
  name: vae
  # train/finetune/predict
  mode: train
  no_test: False
  modelprm: ./modelprms/vae.ckpt
  logoffline: False
  scale_lr: True