model:
  target: lib.models.resvae.ResVAE
  params:
    embed_dim: 4
    schedulerconfig:
      # エポック数
      # t_initial: 200
      # warmup_t: 5
      t_initial: 1000000 # 学習ステップ数
      warmup_t: 4000 # warmupステップ数
      ae:
        target: timm.scheduler.CosineLRScheduler
        params:
          warmup_lr_init: 1.0e-7
          lr_min: 5.0e-7
      disc:
        target: timm.scheduler.CosineLRScheduler
        params:
          warmup_lr_init: 1.0e-7
          lr_min: 5.0e-7

    optconfig:
      ae:
        target: torch.optim.AdamW
        params:
          lr: 4.0e-6
          betas: [0.9, 0.999]
          weight_decay: 0.01
      disc:
        target: torch.optim.AdamW
        params:
          lr: 4.0e-6
          betas: [0.9, 0.999]
          weight_decay: 0.01

    lossconfig:
      target: lib.modules.losses.LPIPSWithDiscriminator
      params:
        # LPIPS loss の割合
        perceptual_weight: 1.0
        # discriminatorのを利用したVAE学習をいつから始めるか
        disc_start: 40001
        kl_weight: 0.001
        disc_weight: 0.14
        disc_loss: hinge


    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: lib.data.video.VideoData
  params:
    data_path: ./datasets/ucf101
    batch_size: 2
    sequence_length: 16
    resolution: 128
    num_workers: 12

lightning:
  callbacks:
    image_logger:
      target: lib.modules.logger.VideoLogger
      params:
        batch_frequency: 1000
        max_videos: 1
        increase_log_steps: True

  modelcheckpoint:
    params:
      every_n_train_steps: 500

  trainer:
    max_steps: 1000000
    benchmark: True
    # truth_batch_size = batch_size * accumulate_grad_batches
    accumulate_grad_batches: 1

opt:
  debug: True
  seed: 334
  gpus: 0, 
  logdir: ./logs
  name: vqvae
  mode: train
  no_test: False
  modelprm: ./modelprms/vae.ckpt
  logoffline: False
  scale_lr: False
  fp16: True